// <auto-generated />
using System;
using AnnoucementScraper.core.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnnoucementScraper.Migrations
{
    [DbContext(typeof(MariaContext))]
    [Migration("20190915181953_Adding-Post-Model")]
    partial class AddingPostModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnnoucementScraper.core.models.AnnTaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("PostTitle");

                    b.Property<string>("PostUrl");

                    b.Property<int>("Replies");

                    b.Property<DateTime>("RetrievedAt");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("TaskStartedAt");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.ToTable("AnnTasks");
                });

            modelBuilder.Entity("AnnoucementScraper.core.models.PostModel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Activity");

                    b.Property<string>("Author");

                    b.Property<string>("Contents");

                    b.Property<int>("Merit");

                    b.Property<int>("Position");

                    b.Property<int>("PostNumber");

                    b.Property<string>("PostedAt");

                    b.Property<DateTime>("RetrievedAt");

                    b.Property<int>("Status");

                    b.Property<int>("TaskId");

                    b.Property<int>("UserId");

                    b.HasKey("id");

                    b.ToTable("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
