// <auto-generated />
using System;
using AnnoucementScraper.core.database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnnoucementScraper.Migrations
{
    [DbContext(typeof(MariaContext))]
    [Migration("20190914212907_AnnTaskModels")]
    partial class AnnTaskModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnnoucementScraper.core.models.AnnTaskModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("PostTitle");

                    b.Property<string>("PostUrl");

                    b.Property<int>("Replies");

                    b.Property<DateTime>("RetrievedAt");

                    b.Property<DateTime?>("TaskStartedAt");

                    b.Property<int>("Views");

                    b.HasKey("Id");

                    b.ToTable("AnnTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
